### ISSUE TITLE
cannot use the library

### ISSUE THREAD

**Issue by muratulashozturk** [avantstay/expo-react-native-camera-kit#1]
Hello, I am trying to import from `expo-react-native-camera-kit` but, it gives the following error:
```
Could not find a declaration file for module 'expo-react-native-camera-kit'. '.../node_modules/expo-react-native-camera-kit/build/main.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/expo-react-native-camera-kit` if it exists or add a new declaration (.d.ts) file containing `declare module 'expo-react-native-camera-kit';
```

How exactly am I supposed to use this library? Could you help, please? Thanks.

@pettomartino

**Comment by pettomartino** [comment]
@muratulashozturk this library is just a plugin to be used wit the https://github.com/teslamotors/react-native-camera-kit.
If you are not using the react-native-camera-kit this library has no use.
If you are indeed using the react-native-camera-kit and doesn't want to eject from expo. 
You need to update your `app.json` (or app.config.js) to use it according to our docs. 

Check more details about Expo Plugins here https://docs.expo.dev/config-plugins/introduction/

**Comment by pettomartino** [comment]
So in theory you shouldn't need to import it anywhere.
